In [1]:
import pandas as pd

In [21]:
names=['Identificador','Numero_agentes','Tipo_red','Agente','Ronda','Estado','Puntaje','Politica','Parametro-0','Parametro-1']
data = pd.read_csv('./data/simulaciones-GRG-100-5.csv', names=names, header=None)
data.head()

,Identificador,Numero_agentes,Tipo_red,Agente,Ronda,Estado,Puntaje,Politica,Parametro-0,Parametro-1
0,2700,100,GRG,0,0,1,1,0,100,0.5
1,2700,100,GRG,0,10,0,0,3,100,0.5
2,2700,100,GRG,0,20,0,0,3,100,0.5
3,2700,100,GRG,0,30,0,0,3,100,0.5
4,2700,100,GRG,0,40,0,0,3,100,0.5

In [ ]:
data['P']

In [22]:
data[(data['Politica']==7) & (data['Ronda']!=0)]['Puntaje'].value_counts()

-1    6769
 1    1036
 0     558
Name: Puntaje, dtype: int64

In [23]:
data[(data['Politica']==7) & (data['Ronda']!=0) & (data['Puntaje']==0)]

,Identificador,Numero_agentes,Tipo_red,Agente,Ronda,Estado,Puntaje,Politica,Parametro-0,Parametro-1
2001,2702,100,GRG,0,10,0,0,7,100,0.5
2021,2702,100,GRG,2,10,0,0,7,100,0.5
2041,2702,100,GRG,4,10,0,0,7,100,0.5
2071,2702,100,GRG,7,10,0,0,7,100,0.5
2081,2702,100,GRG,8,10,0,0,7,100,0.5
...,...,...,...,...,...,...,...,...,...,...
85991,2785,100,GRG,99,10,0,0,7,100,0.5
85993,2785,100,GRG,99,30,0,0,7,100,0.5
85995,2785,100,GRG,99,50,0,0,7,100,0.5
85997,2785,100,GRG,99,70,0,0,7,100,0.5
85999,2785,100,GRG,99,90,0,0,7,100,0.5